<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>F_search_country</name>
   <tag></tag>
   <elementGuidId>a04231b0-6912-4e35-9398-5284dc65d8fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[2]/div/div[1]/div[1]/div[1]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//*[@id=&quot;search-type&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
